(exec 0 (, $x)
        (, 0
           (exec 0 (, 0)
                   (O 
                      (+ (yes))
                      (+ (exec 0 (, (yes)) 
                              (, 2
                                 (exec 0 (, 2)
                                         (, 3)
                                 )
                              )
                      ))
                   )
           )
        )
)